<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:sqlDatabaseMetamodel="http://www.example.org/sqlDatabaseMetamodel">
  <sqlDatabaseMetamodel:Table name="Company" primaryKey="/7">
    <columns name="registrationNumber" constraintTypeSQL="CHECK"/>
    <columns name="CompanyEmployee" constraintTypeSQL="UNIQUE"/>
    <columns name="CompanyProject"/>
  </sqlDatabaseMetamodel:Table>
  <sqlDatabaseMetamodel:Table name="Employee" primaryKey="/8" foreignKeys="/4 /5">
    <columns name="EmployeeName" dataType="VARCHAR" constraintTypeSQL="CHECK"/>
    <columns name="EmployeeAge"/>
    <columns name="EmployeeAddress"/>
    <columns name="postalCode"/>
    <columns name="cityName" dataType="VARCHAR"/>
    <columns name="streetName" dataType="VARCHAR"/>
  </sqlDatabaseMetamodel:Table>
  <sqlDatabaseMetamodel:Table name="Department" primaryKey="/9">
    <columns name="departmentName" dataType="VARCHAR"/>
  </sqlDatabaseMetamodel:Table>
  <sqlDatabaseMetamodel:ForeignKey name="ProjectCompanyRelationship" referencedTable="/0"
      referencedColumn="/0/@columns.2"/>
  <sqlDatabaseMetamodel:ForeignKey name="EmployeeCompanyRelationship" referencedTable="/0"
      referencedColumn="/0/@columns.1"/>
  <sqlDatabaseMetamodel:ForeignKey name="EmployeeDepartmentRelationship" referencedTable="/2"
      referencedColumn="/9"/>
  <sqlDatabaseMetamodel:Table name="Project" primaryKey="/10" foreignKeys="/3">
    <columns name="Name" dataType="VARCHAR"/>
  </sqlDatabaseMetamodel:Table>
  <sqlDatabaseMetamodel:PrimaryKey name="Name" dataType="VARCHAR" isNullable="false"
      isAutoIncrement="true" constraintTypeSQL="UNIQUE"/>
  <sqlDatabaseMetamodel:PrimaryKey name="EmployeeID" isNullable="false" isAutoIncrement="true"
      constraintTypeSQL="UNIQUE"/>
  <sqlDatabaseMetamodel:PrimaryKey name="departmentID" isNullable="false" isAutoIncrement="true"/>
  <sqlDatabaseMetamodel:PrimaryKey name="projectID" isNullable="false" isAutoIncrement="true"/>
</xmi:XMI>
